joint_groups:
  wrist:
    joints:
      - joint5
      - joint6
      - joint7
    sync_read:
      - position
    sync_write:
      - velocity

joint5: { id : 6, operating_mode: 1, pos_limit_margin: 0.524}
joint6: { id : 7, operating_mode: 1, pos_limit_margin: 0.524}
joint7: { id : 8, operating_mode: 1, pos_limit_margin: 0.524}
