joint_groups:
  wrist:
    joints:
      - joint5
      - joint6
      - joint7
    sync_read:
      - position
    sync_write:
      - current

joint5: { id : 6, operating_mode: 0, pos_limit_margin: 0.524, current_limit_margin: 3.17}
joint6: { id : 7, operating_mode: 0, pos_limit_margin: 0.524, current_limit_margin: 3.17}
joint7: { id : 8, operating_mode: 0, pos_limit_margin: 0.524, current_limit_margin: 3.17}
