joint_groups:
  forearm:
    joints:
      - joint5
      - joint6
      - joint7
    sync_read:
      - position
      - velocity
    sync_write:
      - velocity
  hand:
    joints:
      - joint_hand
    sync_read:
      - position
      - velocity
    sync_write:
      - velocity


joint5: { id : 6, operating_mode: 1 }
joint6: { id : 7, operating_mode: 1 }
joint7: { id : 8, operating_mode: 1 }
joint_hand: { id : 9, operating_mode: 1 }
