joint_groups:
  right_wrist:
    joints:
      - right_arm_joint6
      - right_arm_joint7
    sync_read:
      - position
    sync_write:
      - current

  left_wrist:
    joints:
      - left_arm_joint6
      - left_arm_joint7
    sync_read:
      - position
    sync_write:
      - current

right_arm_joint6: { id : 7, operating_mode: 0, pos_limit_margin: 1.047, current_limit_margin: 3.18}
right_arm_joint7: { id : 8, operating_mode: 0, pos_limit_margin: 1.047, current_limit_margin: 3.18}
left_arm_joint6: { id : 15, operating_mode: 0, pos_limit_margin: 1.047, current_limit_margin: 3.18}
left_arm_joint7: { id : 16, operating_mode: 0, pos_limit_margin: 1.047, current_limit_margin: 3.18}
