joint_groups:
  arm:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7
    sync_read:
      - position
      - velocity
      - current
      - voltage
      - temperature
  hand:
    joints:
      - joint_hand


joint1: { id : 2, operating_mode: 3 }
joint2: { id : 3, operating_mode: 3 }
joint3: { id : 4, operating_mode: 3 }
joint4: { id : 5, operating_mode: 3 }
joint5: { id : 6, operating_mode: 3 }
joint6: { id : 7, operating_mode: 3 }
joint7: { id : 8, operating_mode: 3 }
joint_hand: { id : 9, operating_mode: 3 }